src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

from blog import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('blog/' , include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome
from posts.views import BlogPostCreate ,BlogPostUpdate
from posts.views import BlogPostDetail , BlogPostDelete



app_name ="posts"

urlpatterns = [
    path('' , BlogHome.as_view(), name='home'),
    path('create/' ,BlogPostCreate.as_view(), name='create'),
    path('<str:slug>/' ,BlogPostDetail.as_view(), name='post'),
    path('edit/<str:slug>/' ,BlogPostUpdate.as_view(), name='edit'),
    path('delete/<str:slug>/' ,BlogPostDelete.as_view(), name='delete'),
]
 

src/posts/models.py
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db import models
from django.urls import reverse



User = get_user_model()



class BlogPost(models.Model):
    title = models.CharField(max_length=255 , unique=True , verbose_name="Titre")
    slug = models.SlugField(max_length=255 , unique=True , blank=True)
    author = models.ForeignKey(User , on_delete=models.SET_NULL , null=True , blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True , null=True)
    published = models.BooleanField(default=False , verbose_name="publié")
    content = models.TextField(blank=True , verbose_name="contenu")
    thumbnail = models.ImageField(blank=True , upload_to='blog')


    class  Meta:
        ordering = ['-created_on']
        verbose_name = "Article" 


    def __str__(self) :
        return self.title
    
    def save(self , *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

        
    @property
    def author_or_default(self):
        return self.author.get_username if self.author else "L'auteur inconnu"
    

    def get_absolute_url(self):
        return reverse("posts:home")
    

src/posts/views.py
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django.views.generic import ListView  , CreateView , UpdateView ,  DetailView , DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from posts.models import BlogPost

class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self) :
        querySet =  super().get_queryset()
        if self.request.user.is_authenticated:
            return querySet
        
        return querySet.filter(published=True)
    
@method_decorator(login_required , name='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title' , 'content',]

@method_decorator(login_required , name='dispatch')
class BlogPostUpdate(UpdateView):
    model = BlogPost 
    template_name = "posts/blogpost_edit.html"
    fields = ['title' , 'content', 'published']

class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"
    
@method_decorator(login_required , name='dispatch')
class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("posts:home")

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
    <title>supprimer un article</title>
{% endblock  %}
    
{% block content %}
    <form  method="post">
        {% csrf_token %}
        <p>Etes-vous sur de vouloir supprimer "{{object}}"?</p>
        <input type="submit" value="Oui , supprimer" class="btn btn-delete">
    </form>
{% endblock  %}
    

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}


{% block title %}
    <title>Ajouter un Article</title>
{% endblock  %}


{% block content %}
    <h1>Ajouter un Article</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Créer" class="btn btn-submit">
    </form>
{% endblock  %}
    
    

src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}


{% block title %}
    <title>{{post.title}}</title>
{% endblock %}


{% block content %}
    <article class="post-detail">
        <h1>{{post.title}}</h1>
        <img src="{{post.thumbnail.url}}" alt="">
        <div>
            {{post.content|linebreaks|safe}}
        </div>
    </article>
{% endblock %}
    
    

src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}


{% block title %}
    <title>Editer un Article</title>
{% endblock  %}


{% block content %}
    <h1>Editer un Article</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="editer" class="btn btn-submit">
    </form>
{% endblock  %}
    
    

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}
        
        {% block title %}
            <title>Accueil</title>
        {% endblock %}
        
        {% block content %}
            <h1>Le Blog de Zrome</h1>
            
            {% for post in posts %}
                <article>
                    <div class="post-title">
                        <h2>{{post.title}}</h2>
                    
                    {% if request.user.is_authenticated %}
                        <div>
                            <a href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
                            <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
                        </div>
                        {% endif %}
                    </div>
                        
                    <h5 class="post-author">Publié par <i>{{post.author.username}}</i> le {{post.created_on}}</h5>
                    <p class="post-excerpt">{{post.content|safe|truncatewords:50}}</p>
                    <form action="{% url 'posts:post' slug=post.slug %}">
                        <button class="btn btn-submit">Lire l'article</button>
                    </form>
                </article>
            {% endfor %}
                

        {% endblock  %}
            
            

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock%}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <a href="{% url 'posts:home' %}">Accuel</a>
        
        {% if request.user.is_authenticated %}
            <a href="{% url 'posts:create' %}">Ajouter un aricle</a>
        {% endif %}
            
    </nav>
    <section id="blog">
        
        {% block content %}
            
        {% endblock %}
            
    </section>
</body>
</html>